/**
 * Generates `docs/protocol.md` from the protocol's zod schemas. Run with
 * `pnpm -F @shellbell/protocol gen:protocol-doc`. Deterministic: running it twice with no schema
 * change produces a byte-identical file, so the generated doc can be committed and diffed like
 * any other file.
 *
 * Walks `CtrlMessageSchema.options` and `InnerMessageSchema.options` (both `z.discriminatedUnion`,
 * so `.options` is the array of per-`type` object schemas), reads each variant's `type` literal,
 * and emits a fenced JSON Schema block per message. `z.toJSONSchema` is called with
 * `{ unrepresentable: "any" }` because the protocol schemas embed byte types (`Bytes(32)` etc.)
 * that it otherwise refuses to convert.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { z } from "zod";
import { CtrlMessageSchema } from "../src/ctrl.js";
import { EnvelopeSchema, FRAME_LIMITS, V2RelayEnvelopeSchema } from "../src/envelope.js";
import { InnerMessageSchema } from "../src/inner.js";
import { NOTIFICATION_LIMITS, NotificationPayloadSchema } from "../src/notification.js";
import { V2RouteControlSchema } from "../src/session-v2-route-wire.js";

const OUT = join(import.meta.dirname, "..", "..", "..", "docs", "protocol.md");

function toJson(schema: z.ZodTypeAny): string {
  return JSON.stringify(z.toJSONSchema(schema, { unrepresentable: "any" }), null, 2);
}

function typeOf(variant: z.ZodTypeAny): string {
  const shape = (variant as unknown as { shape: { type: { value: string } } }).shape;
  return shape.type.value;
}

function renderUnion<T extends z.ZodTypeAny>(title: string, options: readonly T[]): string {
  const parts = [`## ${title}\n`];
  for (const variant of options) {
    const t = typeOf(variant);
    parts.push(`### \`${t}\`\n\n\`\`\`json\n${toJson(variant)}\n\`\`\`\n`);
  }
  return parts.join("\n");
}

const byteLimitRows = [
  ["unauthenticated", `${FRAME_LIMITS.unauth} B (4 KB)`],
  ["any `ctrl` frame", `${FRAME_LIMITS.ctrl} B (16 KB)`],
  ["`e2e` from phone", `${FRAME_LIMITS.e2eFromPhone} B (64 KB)`],
  ["`e2e` from agent", `${FRAME_LIMITS.e2eFromAgent} B (1 MB)`],
]
  .map(([state, max]) => `| ${state} | ${max} |`)
  .join("\n");

const closeCodeRows = [
  ["4001", "auth failed"],
  ["4003", "bad pairing message"],
  ["4004", "unpaired"],
  ["4005", "superseded (duplicate identity connected)"],
  ["4400", "malformed frame"],
  ["4403", "forbidden for role"],
  ["4408", "unauth/pairing timeout"],
  ["4413", "frame too large"],
  ["4429", "rate limited"],
]
  .map(([code, meaning]) => `| \`${code}\` | ${meaning} |`)
  .join("\n");

const doc = `# Protocol reference

> Generated by \`packages/protocol/scripts/gen-protocol-doc.ts\` from the zod schemas in
> \`packages/protocol/src/ctrl.ts\`, \`packages/protocol/src/inner.ts\` and
> \`packages/protocol/src/envelope.ts\`. Do not hand-edit this file. Run
> \`pnpm -F @shellbell/protocol gen:protocol-doc\` and commit the result. Current prose references:
> [design and security](architecture/design.md), [connections](how-shellbell-connects.md)
> and [secure v2](architecture/direct-transport-wire-v2.md).

## Envelope

Every WebSocket frame is binary CBOR (\`cborg\`, with \`{ ignoreUndefinedProperties: true }\` so
optional fields never appear on the wire), except protocol-level ping/pong control frames (agent
keepalive) and the literal text frames \`"ping"\` / \`"pong"\` (phone keepalive while
foregrounded). Every decoded object is validated with zod before use; invalid frames are dropped
(agent/app) or close the socket with \`4400\` (relay).

\`\`\`json
${toJson(EnvelopeSchema)}
\`\`\`

For v1, \`to\` is required when \`t\` is \`"e2e"\`. \`seq\` is used by \`e2e\` frames only (\`ctrl\` frames
send \`0\`). For \`e2e\` frames, \`body\` is \`{ n: bytes(24), c: bytes }\`; for \`ctrl\` frames it is
one of the Ctrl messages below.

## Experimental v2 opaque relay carrier

The relays can route this versioned envelope between already authenticated paired endpoints.
Its \`body\` is an opaque encoded v2 session frame, limited to 61,000 bytes. There is no outer
JavaScript-number sequence counter. Owner test builds can opt into v2 bootstrap and direct transport. Default new-pair
connections still use v1; upgraded pairs require v2. See \`docs/architecture/direct-transport-wire-v2.md\`.

\`\`\`json
${toJson(V2RelayEnvelopeSchema)}
\`\`\`

## Experimental v2 route coordination

After mutual Noise confirmation and durable v2 floor persistence, encrypted relay
frames carry bounded CBOR arrays: \`["shellbell-v2-route-payload", kind, body]\`.
The kind is \`terminal\` (at most 59,000 bytes), \`signal\` (at most 30,000 bytes),
or \`control\` (at most 512 encoded bytes). Total plaintext is limited to 60,000 bytes.
Only the committed route admits terminal records. Signaling and the four-phase
prepare/prepared/commit/committed exchange use the authenticated relay session.
A direct candidate requires verified native DTLS and fresh Noise keys. An ambiguous
commit closes routes; recovery uses a fresh relay session and never replays input.

\`control\` body:

\`\`\`json
${toJson(V2RouteControlSchema)}
\`\`\`

## Byte limits

Enforced before decoding. Exceeding a limit closes the socket with \`4413\`.

| Socket state | Max frame |
|---|---|
${byteLimitRows}

## Rate limit

Core-handled control and encrypted messages use a per-socket token bucket of
**60 messages/s, burst 200**. Exceeding it closes the socket with \`4429\`.
WebSocket protocol-level ping/pong frames are outside core admission. Literal text
\`"ping"\` / \`"pong"\` keepalive is adapter-handled: Cloudflare uses platform
auto-response, and Node replies before the core bucket. Node frame/queue limits
still apply; [heartbeat rate admission](architecture/extensibility.md#relay-heartbeat-admission)
remains an explicit hardening task.

${renderUnion("Ctrl messages", CtrlMessageSchema.options)}
${renderUnion("Inner messages", InnerMessageSchema.options)}
## Private notification context v1

Capability: \`notify-context-v1\`. Never enable until native delivery and encrypted
enrollment are acknowledged. Legacy peers continue receiving \`notify\` alerts.
Each recipient box is AES-256-GCM ciphertext with a random 12-byte nonce and an
appended 16-byte tag. Only a notification-specific derived key decrypts it.
HKDF-SHA256 input is K_pair; salt is UTF-8 \`shellbell-notification-v1\`; info is
UTF-8 JSON array \`[computerFp, phoneFp, generation]\`; output is 32 bytes.
Generation is canonical unpadded base64url of 16 random bytes.
AAD is UTF-8 JSON array \`["shellbell-notification-v1", computerFp, phoneFp,
generation, sessionId, eventId]\`. Inner routing fields must equal outer fields.

Plaintext limit: ${NOTIFICATION_LIMITS.plaintextBytes} UTF-8 bytes, including JSON.
Ciphertext limit: ${NOTIFICATION_LIMITS.ciphertextBytes} bytes, including tag.
Sequence is canonical positive decimal u64. Native receivers additionally check
recipient identity, generation, expiry, revocation and per-session replay state.
Notification boxes never share terminal connection keys or sequence counters.
Schema refinements reject control/bidi/lone-surrogate labels, noncanonical byte
encoding, invalid time windows and aggregate size overflow.

Decrypted payload (never plaintext in relay messages):

\`\`\`json
${toJson(NotificationPayloadSchema)}
\`\`\`

## WebSocket close codes

| Code | Meaning |
|---|---|
${closeCodeRows}
`;

writeFileSync(OUT, doc);
console.log(`wrote ${OUT}`);
